FROM node:18.16.0 as build-stage

WORKDIR /var/jenkins_home/workspace/BMLOVE/frontend

COPY package*.json .
RUN npm install

COPY . .
RUN npm run build

COPY . .
EXPOSE 3000

ENTRYPOINT ["npx", "serve", "-s", "build"]