FROM openjdk:11-jdk

WORKDIR /var/jenkins_home/workspace/bmlove/backend

ARG JAR_FILE_PATH=build/libs/love-0.0.1-SNAPSHOT.jar

COPY $JAR_FILE_PATH app.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]