FROM openjdk:11-jdk

WORKDIR /var/jenkins_home/workspace/BMLOVE/imageserver

RUN mkdir images

ARG JAR_FILE_PATH=build/libs/imageserver-0.0.1-SNAPSHOT.jar

COPY $JAR_FILE_PATH imageserver.jar

EXPOSE 8081

ENTRYPOINT ["java", "-jar", "imageserver.jar"]